### PR TITLE
Fix copy time.Time with DeepCopy

### LINKED ISSUE #98: DeepCopy doesn't Copy time.Tme Fields
## Reproducible Example

https://play.golang.org/p/AppdcsQyQxI

```
package main

import (
	"testing"
	"time"

	"github.com/jinzhu/copier"
	"github.com/stretchr/testify/assert"

)

func TestDeepCloneTime(t *testing.T) {

	// Build Test data.
	user := User {
		Profile: Profile{
			Name: "Alex",
		},
		CreatedAt: time.Now(),
	}
	var userView UserView


	// Copy with ignore & deep copy.
	copier.CopyWithOption(&userView, &user, copier.Option{
		IgnoreEmpty: true,
		DeepCopy:    true,
	})
	
	// Ensure CreatedAt was copied. 
	assert.Equal(t, user.CreatedAt.String(), userView.CreatedAt.String())
}

// Struct definitions for testing.
type Profile struct{
	Name string
}

type User struct {
	Profile Profile
	CreatedAt time.Time
}

type UserView struct {
	Profile Profile
	CreatedAt time.Time
}

```

## Description

`time.Time` fields don't copy over when using DeepCopy: true.

This is likely a duplicate issue of https://github.com/jinzhu/copier/issues/97 but that was about "nested structs" so it seemed just different enough. If it is a duplicate or this is the desired behavior please feel free to close this issue.

### PR DESCRIPTION
**Pull request by aaron0x**
fix #98 and #97

### CODE REVIEW

**Comment by jordanernult** [comment]
Hi @jinzhu,
Could you please, have a look to this PR.
This branch works well for me as the master doesn't.

Best Regards

**Comment by BatmanAoD** [comment]
I don't believe the problem is with `time.Time` but with the handling of private fields in general. It's impossible to deep-copy private fields using reflection, but the deep-copy logic should at least do a _shallow_ copy of all public fields, which would make `time.Time` and other shallow-copyable structs with private members behave correctly.

**Comment by aaron0x** [comment]
> I don't believe the problem is with `time.Time` but with the handling of private fields in general. 
yes, I agree the problem is caused by unexported fields.
Since you have provided a general solution, I will just close this one.
Good job! @BatmanAoD

**Comment by maeglindeveloper** [comment]
Hey everyone, 
I don't think this issue is fixed @jinzhu 
see the following code [https://go.dev/play/p/Lrcq_MhsH7t](url)
using the latest version.
This is only happening when using deep copy option.

**Comment by BatmanAoD** [comment]
@maeglindeveloper That example works now; I suspect it failed originally because the fix hadn't been included in a release tag yet.

**Pull request closed without merging**
