### PR TITLE
Full support sql.Null* structs on both sides. Copy to Scanner interface and from Valuer interface. 

### PR DESCRIPTION
**Pull request by timsolov**
Right copy of:

`sql.Null*` -> generic types

* `sql.NullString` -> `string`
* `sql.NullTime` -> `time.Time`
* etc...

`sql.Null*` -> ptr to generic types

* `sql.NullString` -> *string
* etc...

Or vice versa:

generic types -> `sql.Null*`

* `string` -> `sql.NullString`
* `time.Time` -> `sql.NullTime`
* etc...

ptr to generic types -> sql.Null*

* `*string` -> `sql.NullString`
* `*time.Time` -> `sql.NullTime`
* etc...

Totally covered by tests.

### CODE REVIEW

**Comment by timsolov** [comment]
> @jinzhu: Hello, would you mind to fixed the conflicting to merge it? thank you

Yes, ready.

**Comment by jinzhu** [comment]
Thank you for your PR.

**Comment by mscansian** [comment]
@jinzhu Hey, is it possible to release a version with this PR included? :)

**Comment by jinzhu** [comment]
> @jinzhu Hey, is it possible to release a version with this PR included? :)

done

**Pull request merged**
